name: CodeRabbit Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run CodeRabbit Review
        uses: coderabbitai/github-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
